fireworks:
  max-explosions: 25
signs:
  max-characters-per-line: 20
books:
  max-book-page-size: 2560
  max-book-total-size-multiplier: 0.98

  ## Enable this if you don't need any book functionality on your server.
  no-books: false

creative:
  ## This can stay disabled unless you give untrustworthy players creative.
  ## If you have any issues with the creative checks, please make a ticket in our
  ## support Discord @ discord.strafe.us or discord.gg/xAEnAUMv9a
  enabled: false

  ## The creative check also checks nbt data nested in block entity tags (containers)
  ## This prevents exploiters from bypassing creative checks by creating containers with the exploit item in it
  ## This value is for the maximum recursion calls, the check is allowed to do per item
  ## If a player reaches a value higher than this, they get kicked.
  ## Increase if false positives occur, too high values could lead to exploitation of the check. Therefore, keep as low as possible.
  max-nbt-recursions: 10

  ## How many items in tags is a block entity tag (container) allowed to contain?
  ## This is to prevent exploiters from sending very large containers, crashing the creative checks.
  ## Same as with max nbt recursions, only increase if false positives occur and do not increase too high.
  max-items-in-containers: 54

  ## Limit all enchantments to a maximum level?
  ## This prevents exploiters from creating hacked items with very high enchantments.
  ## Increase max level or set to -1 to disable
  enchantments:
    max-level: 5

  ## These are the limits for potions that players can create in creative mode.
  ## This prevents exploiters from creating troll potions, (creative) kill potions etc.
  potions:
    max-potion-effects: 5
    max-potion-effect-duration-ticks: 9600
    max-potion-effect-amplifier: 10
    allow-negative-effect-amplifier: false

limits:
  ## There is no perfect value for this.
  ## In order to prevent people getting kicked for lag, the max PPS is higher than shown below.
  ## Every server is different, you'll have to find a good value yourself.
  ## I got this value by assuming a player is clicking 20 CPS, moving, and receiving 2 transactions a tick.
  ## I am also assuming a player could possibly lagspike for 15 seconds, allowing them to send 1200 packets in one second.
  max-packets-per-second: 500

  ## This is the maximum readable bytes a ByteBuf is allowed to contain.
  ## You might want this lower or higher depending on your server and server version.
  ## Every server is different, you'll have to find a good value yourself.
  ## Set to -1 to disable
  ## This value is doubled internally for 1.7 players due to them not having packet compression as far as I'm aware, I could be wrong.
  max-bytes: 64000
  max-bytes-per-second: 256000
spam:
  ## Packet names can be found @ https://wiki.vg/Protocol in the Serverbound section.
  ## Valid format: HELD_ITEM_CHANGE or HELD ITEM CHANGE (Capitalization does not matter.)
  multipliers:
    PLAYER_POSITION: 0.5
    PLAYER_POSITION_AND_ROTATION: 0.5
    PLAYER_ROTATION: 0.5
    PLAYER_FLYING: 0.5

    HELD_ITEM_CHANGE: 1.0
    ANIMATION: 1.0

commands:
  ## This should be a list of commands you do not want executed on your server.
  ## Any chat message or tab completion starting with these will be blocked.
  ## Any player with the command-bypass permission set below will be able to use these commands.
  ## If a command already has a permission required by that plugin to access it, then you do not need to put it here.
  - "//calc"
  - "//calculate"
  - "//eval"
  - "//evaluate"
  - "//solve"
  - "//asc"
  - "//ascend"
  - "//desc"
  - "//descend"
  - "/to"
  - "/hd readtext"
  - "/holo readtext"
  - "/hologram readtext"
  - "/holograms readtext"
  - "/holographicdisplays readtext"
  - "/pex promote"
  - "/pex demote"
  - "/promote"
  - "/demote"
  - "/execute"
  - "/mvhelp"
  - "/mv"

disabled-checks:
## Checks can be found here, this is just a simple list. https://github:com/jtJava/Titanium/tree/master/src/main/java/me/jaden/titanium/check/impl
## I would prefer if you would report issues you have with checks to me, but if you need immediate changes, then you should disable it here.
## - "SpamA"


options:
  ## This makes it so players will only be kicked if cancelling the packet will not completely ruin their gameplay or their connection.
  only-necessary-kicks: true

permissions:
  command-bypass: "titanium.commandbypass"
  notification: "titanium.notification"

messages:
  disconnect-message: "&7(&eTitanium&7) &fYou have been disconnected due \n&fto sending harmful packets."
  staff-notification: "&7(&eTitanium&7) &f%player% &7flagged &f%checkname% "
  staff-notification-info: "&7(&e%info%&7)" ## This will be added to the end of the above message if there is info present.
  blocked-command-message: "Unknown command. Type \"/help\" for help."
